Added SYSTEM_CHAT and DISGUISED_CHAT to translation packet adapter
MCMDEV/i18n pull request #4
Opened 2023-08-07 15:05 UTC by paaulhier

2023-08-07 15:10 UTC, MCMDEV requested changes

2023-08-07 15:10 UTC, MCMDEV commented on i18n-paper/src/main/java/de/helixdevs/i18n/paper/protocollib/ChatAdapter.java
> +        var packet = event.getPacket();
No var. Use typed variables

2023-08-07 15:10 UTC, MCMDEV commented on i18n-paper/src/main/java/de/helixdevs/i18n/paper/protocollib/util/ReflectiveAdventureComponentConverter.java
> +public class ReflectiveAdventureComponentConverter {
Use https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/AdventureComponentConverter.java#

2023-08-07 15:10 UTC, MCMDEV commented on i18n-paper/src/main/java/de/helixdevs/i18n/paper/protocollib/ITranslationAdapter.java
> +        Bukkit.getLogger().info("Translation:" + gsonComponentSerializer.serialize(component));
Remove this debug

2023-08-07 15:10 UTC, MCMDEV commented on i18n-paper/src/main/java/de/helixdevs/i18n/paper/protocollib/ITranslationAdapter.java
> +        var component = GlobalTranslator.render(gsonComponentSerializer.deserialize(wrappedChatComponent.getJson()), player.locale());
Same thing with var here

2023-08-07 15:18 UTC, paaulhier commented on i18n-paper/src/main/java/de/helixdevs/i18n/paper/protocollib/ITranslationAdapter.java
> +        var component = GlobalTranslator.render(gsonComponentSerializer.deserialize(wrappedChatComponent.getJson()), player.locale());
done

2023-08-13 10:18 UTC, MCMDEV commented
Is this tested?

2023-08-13 10:45 UTC, paaulhier commented
it is

2023-08-22 08:29 UTC, merged